CREATE TABLE IF NOT EXISTS `AUDIT_LOG` (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  CUSTOMER_NUMBER VARCHAR(250) NOT NULL,
  PAYLOAD  VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS `ERROR_LOG` (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ERROR_TYPE VARCHAR(250) NOT NULL,
  ERROR_DESCRIPTION  VARCHAR(250) NOT NULL,
  PAYLOAD VARCHAR(250) NOT NULL
);